### ISSUE TITLE
No wifi?

### ISSUE THREAD

**Issue by Swiftnesses** [Dafang-Hacks/rootfs#9]
Hi,

For now I'm using the xaiofang1s_64mb_v2.bin opensource bootloader (the v1 didn't boot and required pins to be set, like you worked out with Paul) - I have asked for a 128MB version, as my board has more RAM.

The issue I have however is I cannot get wifi to connect, I have edited the file in /etc/ but no luck, any ideas?

**Comment by Swiftnesses** [comment]
Solved by uncommenting line in /etc/init.d/rcS under start network.

**Comment by mikolaj-kow** [comment]
@EliasKotlyar why don't put this information in manual (install_sdcard.md)?
